#!/bin/bash

# Copyright (C) 2016-Present Pivotal Software, Inc. All rights reserved.
# This program and the accompanying materials are made available under the terms of the under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

set -eu

pushd $(dirname $0)/../..

echo "Syncing Go Packages"

./scripts/sync-package-specs

echo "Checking for changes in package specs"
set +e
git diff --exit-code packages
diffres=$?
set -e

if [[ "$diffres" -ne 0 ]]; then
  echo "\033[0;31mThere are changes in your package specs, most likely due to sync-package-specs updating them, please review & add these before committing. If the changes are expected, stash them before this commit.\033[0m"
  exit 1
fi

popd
