#!/usr/bin/env bash

set -e

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"

VBOX_HOME="${BASE_DIR}/../vbox/artifacts"

export BOSH_ENVIRONMENT BOSH_CA_CERT BOSH_CLIENT BOSH_CLIENT_SECRET BOSH_NON_INTERACTIVE BOSH_DEPLOYMENT

BOSH_ENVIRONMENT='https://192.168.50.6:25555'
BOSH_CA_CERT="$(mktemp)"
BOSH_CLIENT='admin'
BOSH_CLIENT_SECRET='admin'
BOSH_NON_INTERACTIVE=true
BOSH_DEPLOYMENT=redis-on-demand-broker

yq -r '.default_ca.ca' "$VBOX_HOME/bosh-vars.yml" > "$BOSH_CA_CERT"

main() {
  upload_release "$BASE_DIR/redis-example-service-release"
  upload_release "$BASE_DIR/redis-example-service-adapter-release"
  upload_release "$BASE_DIR/.."
  deploy
  wait_for_route
  bosh run-errand register-broker
}

wait_for_route() {
  echo -n "waiting broker route"
  while ! curl https://redis-on-demand-broker.bosh-lite.com -k -s | grep -q "Not Authorized"; do
    echo -n "."
  done
  echo ""
}

upload_release() {
  local release_path="${1:?}"

  ( cd "$release_path" || exit 1
    bosh sync-blobs
    bosh create-release --force
    bosh upload-release --rebase
  )
}

deploy() {
  bosh \
    deploy "$BASE_DIR/deployment/base_odb_manifest.yml" \
      --ops-file="$BASE_DIR/deployment/operations/redis.yml" \
      --ops-file="$BASE_DIR/deployment/operations/redis_example_service_catalog.yml" \
      --vars-file="$BASE_DIR/deployment/vars-files/redis-example-service-adapter-vars.yml" \
      --vars-file="$VBOX_HOME/broker-deployment-vars.yml" \
      --var=broker_deployment_name="$BOSH_DEPLOYMENT" \
      --var=broker_uri="redis-on-demand-broker.bosh-lite.com" \
      --var=service_release_version="$(get_latest_version_of "redis-service")" \
      --var=stemcell_alias=default \
      --var=service_catalog_service_name="redis" \
      --var=service_catalog_id="DED9ABA5-9AF7-436C-8C9F-80ADDB1FD6D0" \
      --var=broker_route_name="redis-route" \
      --no-redact
}

get_latest_version_of() {
  local release_name="${1:?}"

  bosh --json releases | \
    jq -r ".Tables[].Rows | map(select(.name == \"$release_name\")) | first | .version"
}

main
